version: '3.7'

networks:
  cloudflare-images-api-network:
    name: cloudflare-images-api-network
    driver: bridge

services:
  application:
    container_name: cloudflare-images-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - cloudflare-images-api-network
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    user: node
    env_file:
      - ./workspace.env
